// ==UserScript==
// @name            Floating Sidebar
// @description     Lightweight script to, make firefox Sidebar Floating also option to pin/unpin the sidebar.
// @author          Bibek Bhusal
// @version         1.1.1b
// @lastUpdated     2026-01-09
// @ignorecache
// @homepage        https://github.com/Vertex-Mods/Floating-Sidebar
// ==/UserScript==


// This file was automatically generated. Do not edit this file directly.
// Any changes made here will be overwritten.
// To make changes, please edit the source files in the repository:
// https://github.com/BibekBhusal0/zen-custom-js
(function (factory) {
  typeof define === 'function' && define.amd ? define(factory) :
  factory();
})((function () { 'use strict';

  function startupFinish(callback) {
    if (document.readyState === "complete") callback();
    else window.addEventListener("load", callback, { once: true });
  }

  const parseElement = (elementString, type = "html") => {
    if (type === "xul") {
      return window.MozXULElement.parseXULToFragment(elementString).firstChild;
    }

    let element = new DOMParser().parseFromString(elementString, "text/html");
    if (element.body.children.length) element = element.body.firstChild;
    else element = element.head.firstChild;
    return element;
  };

  const escapeXmlAttribute = (str) => {
    if (typeof str !== "string") return str;
    return str
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&apos;");
  };

  const svgToUrl = (iconSVG) => {
    return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(iconSVG)}`;
  };

  const icons = {
    pin: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" stroke="context-fill light-dark(black, white)" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 17v5M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1a2 2 0 0 0 0-4H8a2 2 0 0 0 0 4a1 1 0 0 1 1 1z"/></svg>`,
    unpin: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" stroke="context-fill light-dark(black, white)" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 17v5m3-12.66V7a1 1 0 0 1 1-1a2 2 0 0 0 0-4H7.89M2 2l20 20M9 9v1.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h11"/></svg>`};

  function setPref(key, value) {
    try {
      const prefService = Services.prefs;
      if (typeof value === "boolean") {
        prefService.setBoolPref(key, value);
      } else if (typeof value === "number") {
        prefService.setIntPref(key, value);
      } else {
        prefService.setStringPref(key, value);
      }
    } catch {
      //ignore
    }
  }

  const getPref = (key, defaultValue) => {
    try {
      const prefService = Services.prefs;
      if (prefService.prefHasUserValue(key)) {
        switch (prefService.getPrefType(key)) {
          case prefService.PREF_STRING:
            return prefService.getStringPref(key);
          case prefService.PREF_INT:
            return prefService.getIntPref(key);
          case prefService.PREF_BOOL:
            return prefService.getBoolPref(key);
        }
      }
    } catch (e) {
      return defaultValue;
    }
    return defaultValue;
  };

  function addPrefListener(name, callback) {
    const modified_callback = () => {
      callback({ value: getPref(name) });
    };
    Services.prefs.addObserver(name, modified_callback);
    return { name, callback };
  }

  function addButton() {
    const header = document.getElementById("sidebar-header");

    if (!header) return;
    const button = parseElement(`<toolbarbutton id="sidebar-pin-unpin"/>`, "xul");
    const PREF_KEY = "extension.sidebar-float";
    const floating = () => getPref(PREF_KEY, false);
    function updateImage() {
      const icon = floating() ? icons["pin"] : icons["unpin"];
      button.setAttribute("image", escapeXmlAttribute(svgToUrl(icon)));
    }
    updateImage();
    addPrefListener(PREF_KEY, updateImage);

    const buttonClick = () => setPref(PREF_KEY, !floating());

    button.addEventListener("click", buttonClick);
    const children = header.children;
    if (children.length > 1) {
      header.insertBefore(button, children[children.length - 1]);
    } else {
      header.appendChild(button);
    }
  }

  startupFinish(addButton);

}));
